#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     09/07/2024
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2024
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
function: Navigation message server
server_name: navigation
log_level: INFO
trace_dir: /data/solidsense/traces
log_module:

features:
    - router_core
    - nmea2000
    - nmea0183
    - can_interface
    - nmea2000_devices
    - couplers:
          - NMEATCPReader

servers:

- Main:
      class: NavigationMainServer
      
- NMEAServer:
    class: NMEAServer
    port: 4500
    nmea2000: dyfmt
    
- gRPCMain:
    class: GrpcServer
    port: 4502
    
- NMEASender:
    class: NMEASenderServer
    port: 4503
    coupler: CANCoupler
    max_silent: 10
    # master: 172.16.0.100
    timeout: 8.0
    
- NMEANetwork:
    class: NMEA2KActiveController
    trace: false
    channel: can0
    max_silent: 60.0
    applications: [ CANCoupler, APSimulator, APEmulator ]


couplers:

- CANCoupler:
    class: DirectCANCoupler

- ScannavReplay:
    class: NMEATCPReader
    address: 192.168.1.21
    port: 3555
    autostart: false
    
services:

- Console:
    class: Console
    server: gRPCMain


publishers:

- TraceOutput:
    class: N2KTracePublisher
    couplers: [CANCoupler]
    # filters: [NMEAOutput]
    filter_select: true
    active: false
    flexible_decode: false

- CanFeed:
    class: Injector
    target: CANCoupler
    couplers: [ScannavReplay]
    active: false

filters:

- RemoveGPS:
     class: NMEA0183Filter
     talker: GP
     formatter: GSV
     type: discard

- DiscardAISGPS:
     class: NMEA2000Filter
     source: 43
     pgn: [129025, 129026]
     type: discard

- AutoPilotN2K:
    class: NMEA2000Filter
    source: 7
    type: discard

- Barometer:
    class: NMEA2000TimeFilter
    source: 52
    pgn: [130310, 130311, 130314]
    type: select
    period: 10.0

- Engine:
    class: NMEA2000Filter
    pgn: [127488, 127489]
    type: select
      
applications:

- APSimulator:
    class: DeviceSimulator
    address: 10
    pgn_list: [129283, 129284, 129285]
    model_id: Auto Pilot

- APEmulator:
    class: AutoPilotEmulator
    address: 10
    model_id: Auto Pilot Emulator